const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const APP = $('#app');
const DBKEY = 'aqar_system_v2';
const DEFAULT_SETTINGS = {
  companyName:'مؤسسة رواد الأفق للاستثمار',
  logo:'logo.png', watermark:'watermark.png',
  phone1:'0500 277 257', phone2:'0552 209 226', email:'rwadalafq@gmail.com', address:'طريق المطار - المملكة العربية السعودية'
};
let state = {view:'home', tab:'active', filter:'الكل', query:'', offerQuery:'', selected:null, editId:null};
let data = loadData();
function loadData(){try{return JSON.parse(localStorage.getItem(DBKEY)) || {settings:DEFAULT_SETTINGS, properties:[], seq:1000}}catch{return {settings:DEFAULT_SETTINGS, properties:[], seq:1000}}}
function saveData(){localStorage.setItem(DBKEY, JSON.stringify(data));}
function toast(t){const el=$('#toast'); el.textContent=t; el.style.display='block'; setTimeout(()=>el.style.display='none',2200)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toLocaleString('ar-SA')}
function esc(v){return (v??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function icon(name){const paths={home:'M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3z',map:'M12 21s7-4.4 7-11a7 7 0 1 0-14 0c0 6.6 7 11 7 11zm0-8.5A2.5 2.5 0 1 0 12 7a2.5 2.5 0 0 0 0 5.5z',ruler:'M4 19 19 4l1 1L5 20z M7 16l1 1 M10 13l1 1 M13 10l1 1 M16 7l1 1',road:'M8 21l2-18h4l2 18m-4-4v-3m0-4V7',compass:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm3 6-2 6-6 2 2-6z',file:'M6 2h8l4 4v16H6z M14 2v5h5',car:'M5 16h14l-2-5H7z M7 16v3 M17 16v3',bed:'M4 11h16v7M4 18V8m0 6h16M8 11V7h6v4',bath:'M5 12h14v3a5 5 0 0 1-5 5H10a5 5 0 0 1-5-5zM7 12V6a2 2 0 0 1 2-2h1',mosque:'M4 20h16V10l-8-5-8 5zm4 0v-6h8v6',school:'M3 20h18V8l-9-5-9 5zm5 0v-6h8v6',tree:'M12 3a4 4 0 0 0-3 6 4 4 0 0 0 0 8h6a4 4 0 0 0 0-8 4 4 0 0 0-3-6zm0 14v4',shop:'M4 10h16l-1-5H5zm2 0v10h12V10',bolt:'M13 2 4 14h7l-1 8 9-12h-7z',phone:'M6 2h12v20H6zM10 18h4',mail:'M3 5h18v14H3zm0 0 9 7 9-7',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z M4 12h2m12 0h2M12 4v2m0 12v2',archive:'M4 4h16v4H4zm2 4h12v12H6z',plus:'M12 5v14M5 12h14',save:'M5 3h14v18H5z M8 3v6h8M8 17h8',share:'M18 8a3 3 0 1 0-2.8-4H15a3 3 0 0 0 .2 1L8.8 8.8A3 3 0 1 0 9 11l6.4 3.8a3 3 0 1 0 .8-1.8L9.8 9.2',edit:'M4 20h4l11-11-4-4L4 16z',search:'M10 18a8 8 0 1 1 5.7-2.3L21 21',trash:'M5 7h14M9 7V5h6v2M8 7l1 14h6l1-14'};return `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.file}"/></svg>`}
function statusClass(s){return s==='متاح'?'available':s==='تحت التفاوض'?'negotiation':s==='تم البيع'?'sold':s==='تم التأجير'?'rented':'archived'}
function activeProps(){return data.properties.filter(p=>state.tab==='archive'?p.archived:!p.archived)}
function filtered(){let arr=activeProps(); if(state.filter!=='الكل') arr=arr.filter(p=>p.type===state.filter); if(state.query.trim()){const q=state.query.trim().toLowerCase(); arr=arr.filter(p=>JSON.stringify(p).toLowerCase().includes(q));} if(state.offerQuery.trim()) arr=arr.filter(p=>String(p.offerNo||'').includes(state.offerQuery.trim())); return arr.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));}
function uniqueTypes(){const list=[...new Set(data.properties.filter(p=>!p.archived && p.type).map(p=>p.type))]; return ['الكل',...list]}
function firstImg(p){return (p.media||[]).find(m=>m.type.startsWith('image'))?.data || ''}
function route(v, extra={}){state={...state,view:v,...extra}; render(); window.scrollTo(0,0)}
function render(){APP.className='app'; if(state.view==='home') return renderHome(); if(state.view==='form') return renderForm(); if(state.view==='detail') return renderDetail(state.selected); if(state.view==='settings') return renderSettings();}
function renderHome(){const types=uniqueTypes(); const props=filtered(); APP.innerHTML=`
 <div class="top"><button class="iconBtn" onclick="route('settings')">${icon('settings')}</button><h1>إدارة العقارات</h1><button class="btn primary" onclick="route('form')">${icon('plus')} إضافة عقار</button><button class="btn" onclick="state.tab='archive';render()">${icon('archive')} الأرشيف</button></div>
 <div class="searchBox">${icon('search')}<input placeholder="بحث شامل في كل التفاصيل: المالك، الحي، الشارع، النوع، المساحة..." value="${esc(state.query)}" oninput="state.query=this.value;render()"></div>
 <div class="searchBox">#<input placeholder="بحث برقم العرض فقط" value="${esc(state.offerQuery)}" oninput="state.offerQuery=this.value;render()"></div>
 <div class="filters">${types.map(t=>`<button class="chip ${state.filter===t?'active':''}" onclick="state.filter='${esc(t)}';render()"><b>${esc(t)}</b><span>${t==='الكل'?data.properties.filter(p=>!p.archived).length:data.properties.filter(p=>!p.archived&&p.type===t).length}</span></button>`).join('')}</div>
 <div class="tabs"><button class="${state.tab==='active'?'active':''}" onclick="state.tab='active';render()">عام (${data.properties.filter(p=>!p.archived).length})</button><button class="${state.tab==='archive'?'active':''}" onclick="state.tab='archive';render()">الأرشيف (${data.properties.filter(p=>p.archived).length})</button></div>
 <div>${props.length?props.map(cardHtml).join(''):'<div class="card empty">لا توجد عقارات مطابقة</div>'}</div>`}
function cardHtml(p){return `<div class="card"><div class="propCard"><div class="thumb">${firstImg(p)?`<img src="${firstImg(p)}">`:''}<span class="status ${statusClass(p.status)}" style="position:absolute;top:6px;right:6px">${esc(p.status||'متاح')}</span></div><div><h2 class="propTitle">${esc(p.title||'عقار بدون اسم')}</h2><div class="meta">${icon('map')} ${esc([p.city,p.district].filter(Boolean).join(' - ')||'بدون موقع')}</div><div class="meta">${icon('ruler')} ${esc(p.area||'-')} م² &nbsp; ${icon('home')} ${esc(p.type||'-')}</div><div class="miniGrid"><div>المساحة<b>${esc(p.area||'-')}</b></div><div>الغرف<b>${esc(p.rooms||'-')}</b></div><div>تحديث<b>${esc(p.updatedText||'-')}</b></div></div></div><div class="offerBadge">رقم العرض<b>${esc(p.offerNo)}</b></div></div><div class="rowActions"><button class="btn" onclick="route('detail',{selected:'${p.id}'})">عرض التفاصيل</button>${p.archived?`<button class="btn" onclick="toggleArchive('${p.id}',false)">نقل إلى العام</button>`:`<button class="btn warn" onclick="toggleArchive('${p.id}',true)">أرشفة</button>`}</div></div>`}
function newProp(){return {id:uid(),offerNo:++data.seq,status:'متاح',media:[],services:[],createdAt:Date.now(),updatedAt:Date.now(),updatedText:today(),archived:false}}
function getP(id){return data.properties.find(p=>p.id===id)}
function renderForm(){let p=state.editId?JSON.parse(JSON.stringify(getP(state.editId))):newProp(); window._editing=p; APP.innerHTML=`<div class="top"><button class="iconBtn" onclick="route('home')">‹</button><h1>${state.editId?'تعديل العقار':'إضافة عقار جديد'}</h1></div>
 <form id="form">
 <section class="formSection"><h2 class="sectionTitle">${icon('file')} الصور والفيديو</h2><div class="mediaRow" id="mediaRow"></div><input id="mediaInput" type="file" accept="image/*,video/*" multiple hidden onchange="addMedia(this.files)"></section>
 ${section('المعلومات الأساسية', ['title:اسم العقار:مثال: فيلا فاخرة بحي النخيل','type:نوع العقار:مثال: فيلا','category:التصنيف:سكني / تجاري','status:الحالة:متاح'])}
 ${section('بيانات الموقع', ['city:المدينة:مثال: الطائف','district:الحي:مثال: الشفاية','street:الشارع:اسم الشارع','mapUrl:رابط الموقع:الصق رابط Google Maps / Apple Maps / إحداثيات'])}
 ${section('بيانات الأرض / العقار', ['area:المساحة:510','length:الطول:25','width:العرض:20','streetWidth:عرض الشارع:20','frontage:واجهة العقار:شمالية','planNo:رقم المخطط:2357','plotNo:رقم القطعة:128'])}
 ${section('بيانات إضافية', ['rooms:عدد الغرف:7','baths:دورات المياه:7','parking:مواقف السيارات:2'])}
 <section class="formSection"><h2 class="sectionTitle">${icon('tree')} الخدمات والوصف</h2><div class="grid"><div class="field span2"><label>الخدمات المتوفرة</label><textarea id="services" placeholder="اكتب كل خدمة في سطر:&#10;مسجد&#10;مدارس&#10;بقالة">${esc((p.services||[]).join('\n'))}</textarea></div><div class="field span2"><label>وصف العقار</label><textarea id="description" placeholder="اكتب وصف العقار التسويقي هنا">${esc(p.description||'')}</textarea></div></div></section>
 <section class="formSection private"><h2 class="sectionTitle">${icon('settings')} معلومات داخلية لا تظهر في المشاركة</h2>${privateFields(p)}</section>
 <div class="footerActions"><button type="button" class="btn" onclick="previewEditing()">معاينة</button><button type="button" class="btn" onclick="saveForm(true)">حفظ وإضافة جديد</button><button type="button" class="btn primary" onclick="saveForm(false)">${icon('save')} حفظ العقار</button></div></form>`; renderMedia();}
function section(title, defs){return `<section class="formSection"><h2 class="sectionTitle">${title}</h2><div class="grid">${defs.map(d=>{let [k,l,ph]=d.split(':');return `<div class="field"><label>${l}</label><input id="${k}" value="${esc(window._editing?.[k]||'')}" placeholder="${esc(ph||'')}"></div>`}).join('')}</div></section>`}
function privateFields(p){const defs=[['ownerName','اسم المالك'],['ownerPhone','رقم المالك'],['brokerName','اسم الوسيط'],['brokerPhone','رقم الوسيط'],['directBrokerPhone','رقم الوسيط المباشر'],['brokerCount','عدد الوسطاء'],['commission','السعي'],['price','السعر'],['lastBid','آخر سومة'],['privateNotes','ملاحظات خاصة']]; return `<div class="grid">${defs.map(([k,l])=>`<div class="field ${k==='privateNotes'?'span4':''}"><label>${l}</label>${k==='privateNotes'?`<textarea id="${k}">${esc(p[k]||'')}</textarea>`:`<input id="${k}" value="${esc(p[k]||'')}">`}</div>`).join('')}</div>`}
function renderMedia(){const row=$('#mediaRow'); if(!row)return; const p=window._editing; row.innerHTML=(p.media||[]).map((m,i)=>`<div class="mediaBox">${m.type.startsWith('video')?`<video src="${m.data}"></video>`:`<img src="${m.data}">`}<button class="x" onclick="removeMedia(${i})">×</button></div>`).join('')+`<label class="uploadBox" for="mediaInput">+ إضافة</label>`}
function addMedia(files){[...files].forEach(f=>{const r=new FileReader();r.onload=()=>{window._editing.media.push({type:f.type,data:r.result,name:f.name});renderMedia()};r.readAsDataURL(f)});}
function removeMedia(i){window._editing.media.splice(i,1);renderMedia()}
function readForm(){const p=window._editing; ['title','type','category','status','city','district','street','mapUrl','area','length','width','streetWidth','frontage','planNo','plotNo','rooms','baths','parking','description','ownerName','ownerPhone','brokerName','brokerPhone','directBrokerPhone','brokerCount','commission','price','lastBid','privateNotes'].forEach(k=>p[k]=$('#'+k)?.value.trim()||''); p.services=($('#services').value||'').split('\n').map(x=>x.trim()).filter(Boolean); p.updatedAt=Date.now(); p.updatedText=today(); return p}
function saveForm(addNew){const p=readForm(); if(state.editId){const i=data.properties.findIndex(x=>x.id===state.editId); data.properties[i]=p}else data.properties.push(p); saveData(); toast('تم الحفظ'); if(addNew) route('form',{editId:null}); else route('detail',{selected:p.id,editId:null})}
function previewEditing(){const p=readForm(); data.properties=data.properties.filter(x=>x.id!==p.id).concat(p); saveData(); route('detail',{selected:p.id,editId:null})}
function renderDetail(id){const p=getP(id); if(!p)return route('home'); const imgs=(p.media||[]); APP.innerHTML=`<div class="top"><button class="iconBtn" onclick="route('home')">‹</button><h1>عرض رقم ${esc(p.offerNo)}</h1><button class="iconBtn">•••</button></div><div class="status ${statusClass(p.status)}">${esc(p.status||'متاح')}</div>
 <div class="card hero">${firstImg(p)?`<img src="${firstImg(p)}">`:''}</div><div class="gallery">${imgs.map(m=>m.type.startsWith('video')?`<video src="${m.data}" controls></video>`:`<img src="${m.data}">`).join('')}</div>
 <section class="formSection"><h2 class="sectionTitle">${esc(p.title||'عقار بدون اسم')}</h2><div class="meta">${icon('map')} ${esc([p.city,p.district].filter(Boolean).join(' - '))}</div><div class="infoGrid">${infoCells(p,['type:نوع العقار','offerNo:رقم العرض','category:التصنيف','status:الحالة','area:المساحة','length:الطول','width:العرض','planNo:رقم المخطط','plotNo:رقم القطعة','streetWidth:عرض الشارع','frontage:واجهة العقار','rooms:عدد الغرف','baths:دورات المياه','parking:مواقف السيارات'])}</div></section>
 <section class="formSection"><h2 class="sectionTitle">وصف العقار</h2><p>${esc(p.description||'لا يوجد وصف')}</p></section>
 <section class="formSection private"><h2 class="sectionTitle">معلومات داخلية لا تظهر في المشاركة</h2><div class="infoGrid">${privateInfo(p)}</div></section>
 <section class="formSection"><h2 class="sectionTitle">${icon('map')} الموقع</h2>${p.mapUrl?`<a class="btn block" href="${esc(normalizeMap(p.mapUrl))}" target="_blank">فتح الموقع في الخرائط</a>`:'<div class="empty">لا يوجد رابط موقع</div>'}</section>
 <div class="footerActions"><button class="btn danger" onclick="toggleArchive('${p.id}',true)">أرشفة</button><button class="btn" onclick="sharePdf('${p.id}')">${icon('share')} مشاركة</button><button class="btn primary" onclick="confirmEdit('${p.id}')">${icon('edit')} تعديل</button></div><div id="printArea"></div><div id="personModal" class="modal"><div class="sheet" id="personSheet"></div></div>`}
function infoCells(p,defs){return defs.map(d=>{let[k,l]=d.split(':'); return `<div class="cell"><small>${l}</small><b>${esc(p[k]||'-')}</b></div>`}).join('')}
function privateInfo(p){return `<div class="cell"><small>المالك</small><button class="clickName" onclick="showPerson('${esc(p.ownerName)}','ownerName')">${esc(p.ownerName||'-')}</button><b>${esc(p.ownerPhone||'')}</b></div><div class="cell"><small>الوسيط</small><button class="clickName" onclick="showPerson('${esc(p.brokerName)}','brokerName')">${esc(p.brokerName||'-')}</button><b>${esc(p.brokerPhone||'')}</b></div><div class="cell"><small>عدد الوسطاء</small><b>${esc(p.brokerCount||'-')}</b></div><div class="cell"><small>السعي</small><b>${esc(p.commission||'-')}</b></div><div class="cell"><small>السعر</small><b>${esc(p.price||'-')}</b></div><div class="cell"><small>آخر سومة</small><b>${esc(p.lastBid||'-')}</b></div><div class="cell"><small>ملاحظات خاصة</small><b>${esc(p.privateNotes||'-')}</b></div>`}
function showPerson(name,field){if(!name)return; const arr=data.properties.filter(p=>p[field]===name); const sheet=$('#personSheet'); sheet.innerHTML=`<h3>العقارات المرتبطة بـ ${esc(name)}</h3><p>الإجمالي: ${arr.length} | النشطة: ${arr.filter(p=>!p.archived).length} | الأرشيف: ${arr.filter(p=>p.archived).length}</p>${arr.map(p=>`<div class="card" style="padding:12px"><b>${p.offerNo} - ${esc(p.title||'بدون اسم')}</b><br><button class="btn" onclick="document.getElementById('personModal').classList.remove('show');route('detail',{selected:'${p.id}'})">فتح العرض</button></div>`).join('')}<button class="btn block" onclick="document.getElementById('personModal').classList.remove('show')">إغلاق</button>`; $('#personModal').classList.add('show')}
function confirmEdit(id){if(confirm('سيتم فتح وضع التعديل على هذا العرض. هل تريد المتابعة؟')) route('form',{editId:id})}
function toggleArchive(id,val){const p=getP(id); if(!p)return; if(val&&!confirm('هل تريد نقل العرض إلى الأرشيف؟'))return; p.archived=val; p.status=val?(p.status==='متاح'?'مؤرشف':p.status):'متاح'; p.updatedAt=Date.now(); p.updatedText=today(); saveData(); render();}
function normalizeMap(v){if(!v)return '#'; if(/^https?:\/\//i.test(v))return v; const m=v.match(/(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)/); if(m)return `https://maps.google.com/?q=${m[1]},${m[2]}`; return `https://maps.google.com/?q=${encodeURIComponent(v)}`}
function sharePdf(id){const p=getP(id); $('#printArea').innerHTML=pdfHtml(p); setTimeout(()=>window.print(),200)}
function pdfHtml(p){const s=data.settings; const imgs=(p.media||[]).filter(m=>m.type.startsWith('image')).map(m=>m.data); const chunks=[]; for(let i=0;i<imgs.length;i+=6)chunks.push(imgs.slice(i,i+6)); const page1=`${pdfSheet(1,`<div class="pdfHeader"><div class="pdfOffer"><small>عرض رقم</small><b>${esc(p.offerNo)}</b></div><div class="pdfTitle"><h1>تقرير عقاري</h1><p>ملف مشاركة رسمي - للاستفسار يرجى التواصل</p></div><div style="text-align:left"><img src="${s.logo}"><b>${esc(s.companyName)}</b></div></div><div class="pdfHeroGrid"><div class="pdfHero">${firstImg(p)?`<img src="${firstImg(p)}">`:''}</div><div class="pdfBox"><h2>معلومات العقار الأساسية</h2><div class="pdfData">${pdfCells(p,['type:نوع العقار','status:حالة العقار','city:المدينة','district:الحي','area:المساحة','frontage:الواجهة','streetWidth:عرض الشارع','planNo:رقم المخطط','plotNo:رقم القطعة'])}</div></div></div><div class="pdfBox"><h2>تفاصيل العقار</h2><table class="pdfTable"><tbody>${rows([['الطول',p.length],['العرض',p.width],['عدد الغرف',p.rooms],['دورات المياه',p.baths],['مواقف السيارات',p.parking],['التصنيف',p.category]])}</tbody></table></div><div class="pdfTwo"><div class="pdfBox"><h2>وصف العقار</h2><div style="padding:6mm;line-height:2">${esc(p.description||'لا يوجد وصف')}</div></div><div class="pdfBox"><h2>الخدمات المتوفرة بالقرب من العقار</h2><div class="pdfServices">${(p.services||[]).slice(0,10).map(x=>`<div>${iconForService(x)}<br>${esc(x)}</div>`).join('')}</div></div></div><div class="pdfTwo"><div class="pdfBox"><h2>رابط الموقع</h2><div class="mapBox">يفتح الموقع عبر الرابط الإلكتروني عند الضغط من التطبيق</div></div><div class="pdfBox"><h2>ملاحظات المشاركة</h2><div style="padding:6mm;line-height:2">السعر والسومة وبيانات المالك والوسطاء غير ظاهرة في هذا الملف، وجميع الاستفسارات عن طريق المؤسسة.</div></div></div>`)};`;
 const imagePages=chunks.map((ch,i)=>pdfSheet(i+2,`<div class="pdfHeader"><div class="pdfOffer"><small>عرض رقم</small><b>${esc(p.offerNo)}</b></div><div class="pdfTitle"><h1>صور العقار</h1><p>صفحة صور إضافية</p></div><div style="text-align:left"><img src="${s.logo}"><b>${esc(s.companyName)}</b></div></div><div class="pdfBox"><h2>صور العقار</h2><div class="pdfImages" style="padding:4mm">${ch.map(src=>`<img src="${src}">`).join('')}</div></div>`)).join(''); return `<div class="pdfPage">${page1}${imagePages}</div>`}
function pdfSheet(n,content){const s=data.settings; return `<section class="pdfSheet"><div class="pdfContent">${content}</div><div class="pageNum">صفحة ${n}</div><footer class="pdfFooter"><div class="fbrand"><img src="${s.logo}"><b>${esc(s.companyName)}</b></div><div>${icon('map')} ${esc(s.address)}</div><div>${icon('mail')} ${esc(s.email)}</div><div>${icon('phone')} ${esc(s.phone1)}<br>${icon('phone')} ${esc(s.phone2)}</div></footer></section>`}
function pdfCells(p,defs){return defs.map(d=>{const[k,l]=d.split(':');return `<div><small>${l}</small><b>${esc(p[k]||'-')}</b></div>`}).join('')}
function rows(arr){return arr.map(([a,b])=>`<tr><th>${esc(a)}</th><td>${esc(b||'-')}</td></tr>`).join('')}
function iconForService(x){return icon(x.includes('مسجد')?'mosque':x.includes('مدرس')?'school':x.includes('حد')?'tree':x.includes('سوق')||x.includes('بقال')?'shop':x.includes('كهرب')?'bolt':'map')}
function renderSettings(){const s=data.settings; APP.innerHTML=`<div class="top"><button class="iconBtn" onclick="route('home')">‹</button><h1>الإعدادات</h1></div><section class="formSection"><h2 class="sectionTitle">الهوية والتواصل</h2><div class="settingsLogo"><img src="${s.logo}"><div><input type="file" id="logoInput" accept="image/*" onchange="loadLogo(this.files[0])"><p style="color:var(--muted)">ارفع شعار المؤسسة الرئيسي. يبقى محفوظ محليًا وداخل النسخة الاحتياطية.</p></div></div><div class="grid"><div class="field span2"><label>اسم المؤسسة</label><input id="companyName" value="${esc(s.companyName)}"></div><div class="field"><label>رقم 1</label><input id="phone1" value="${esc(s.phone1)}"></div><div class="field"><label>رقم 2</label><input id="phone2" value="${esc(s.phone2)}"></div><div class="field span2"><label>البريد</label><input id="email" value="${esc(s.email)}"></div><div class="field span2"><label>العنوان</label><input id="address" value="${esc(s.address)}"></div></div><button class="btn primary block" onclick="saveSettings()">حفظ الإعدادات</button></section><section class="formSection"><h2 class="sectionTitle">النسخ الاحتياطي</h2><button class="btn block" onclick="exportBackup()">تصدير نسخة احتياطية</button><br><br><input type="file" id="backupInput" accept=".aqarbackup,.json" onchange="importBackup(this.files[0])"><p style="color:var(--muted)">النسخة تشمل العقارات والصور والشعار والأرشيف وكل البيانات الخاصة.</p></section>`}
function loadLogo(f){if(!f)return; const r=new FileReader(); r.onload=()=>{data.settings.logo=r.result; data.settings.watermark=r.result; saveData(); renderSettings()}; r.readAsDataURL(f)}
function saveSettings(){['companyName','phone1','phone2','email','address'].forEach(k=>data.settings[k]=$('#'+k).value.trim()); saveData(); toast('تم حفظ الإعدادات')}
function exportBackup(){const blob=new Blob([JSON.stringify(data)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='AqarBackup-'+Date.now()+'.aqarbackup'; a.click(); URL.revokeObjectURL(a.href)}
function importBackup(f){if(!f)return; if(!confirm('سيتم استبدال البيانات الحالية بالنسخة الاحتياطية. هل تريد المتابعة؟'))return; const r=new FileReader(); r.onload=()=>{try{data=JSON.parse(r.result); saveData(); toast('تم الاستيراد'); route('home')}catch{alert('ملف النسخة غير صالح')}}; r.readAsText(f)}
function seed(){if(data.properties.length)return; data.properties.push({id:uid(),offerNo:1001,title:'قصر فخم شعبي 100 متر',type:'قصر',category:'سكني',status:'متاح',city:'الحوية',district:'الرحبة',area:'100',length:'64',width:'15',streetWidth:'800',frontage:'شمال',planNo:'850',plotNo:'5',rooms:'900',baths:'1',parking:'لا يوجد',description:'قصر على نص شارع، موقع مميز وقريب من الخدمات. الوصف يظهر هنا بشكل رسمي ومرتب في ملف المشاركة.',services:['لاونج','محل سمك','مخبز','حائط ربايع','محل سكراب'],ownerName:'مخفي',ownerPhone:'05xxxxxxxx',brokerName:'مخفي',brokerPhone:'05xxxxxxxx',brokerCount:'1',commission:'2.5%',price:'خاص',lastBid:'خاص',privateNotes:'العقار قابل للتفاوض',mapUrl:'https://maps.google.com',media:[],createdAt:Date.now(),updatedAt:Date.now(),updatedText:today(),archived:false}); data.seq=1001; saveData()}
seed(); render();
